OnlineShoppingStore/Controllers/MyAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using OnlineShoppingStore.Models;

namespace OnlineShoppingStore.Controllers
{
    public class MyAdminController : Controller
    {
        string connectionString = @"Data Source = DESKTOP-4P22BP2;  Initial Catalog =OnlineShoppingStore;  Integrated Security  = true";

        // GET: MyAdmin
        public ActionResult Index()
        {
            return View();
        }public ActionResult Dashboard()
        {
            return View();
        }

        public ActionResult Testop()
        {
            return View();
        }

        public List<SelectListItem> GetCategory()
        {
            List<SelectListItem> list = new List<SelectListItem>();

            DataTable dtblProduct = new DataTable();
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("Select * from Category", sqlcon);
                sqlDa.Fill(dtblProduct);

                foreach (DataRow item in dtblProduct.Rows)
                {
                    list.Add(new SelectListItem { Value = item["CategoryId"].ToString(), Text = item["CategoryName"].ToString() });

                }
            }
            return list;
        }

        public ActionResult MyDashbord()
        {
            return View();
        }
        // GET: MyAdmin
        [HttpGet]
        public ActionResult MyProducts()
        {
            DataTable dtblProduct = new DataTable();
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("Select * from Product", sqlcon);
                sqlDa.Fill(dtblProduct);

            }

            return View(dtblProduct);
        }
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.CategoryList = GetCategory();

            return View(new Adminproductlist());
        }


        [HttpPost]
        public ActionResult Create(Adminproductlist productlist, HttpPostedFileBase file)
        {


            string pic = null;
            if (file != null)
            {


                pic = System.IO.Path.GetFileName(file.FileName);
                string path = System.IO.Path.Combine(Server.MapPath("~/ProductImg/"), pic);
                file.SaveAs(path);

            }

            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                string query = "Insert into Product  Values(@CategoryId,@ProductName,@ProductDescription,@ProductQuantity,@ProductPrice,@ProductImage,@IsAvilable,@ProductColor,@DiscountAvailable,@Taglistid,@ProductSize) ";
                SqlCommand sqlCmd = new SqlCommand(query, sqlcon);
                sqlCmd.Parameters.AddWithValue("@CategoryId", productlist.CategoryId);

                sqlCmd.Parameters.AddWithValue("@ProductName", productlist.ProductName);

                sqlCmd.Parameters.AddWithValue("@ProductDescription", productlist.Descriptions);

                sqlCmd.Parameters.AddWithValue("@ProductQuantity", productlist.ProductQuantity);

                sqlCmd.Parameters.AddWithValue("@ProductPrice", productlist.ProductPrice);

                sqlCmd.Parameters.AddWithValue("@ProductImage", pic);

                sqlCmd.Parameters.AddWithValue("@IsAvilable", productlist.Isavaiable);

                sqlCmd.Parameters.AddWithValue("@ProductColor", productlist.ProductColor);

                sqlCmd.Parameters.AddWithValue("@DiscountAvailable", productlist.Isdiscount);

                sqlCmd.Parameters.AddWithValue("@Taglistid", productlist.Taglist);

                sqlCmd.Parameters.AddWithValue("@ProductSize", productlist.ProductSize);
                sqlCmd.ExecuteNonQuery();
            }


            return RedirectToAction("MyProducts");
        }




        [HttpGet]
       // [Route("MyAdmin/Edit/{ProductId}")]
        public ActionResult Edit(int id)
        {
            Adminproductlist productlist = new Adminproductlist();
            DataTable dtblProduct = new DataTable();
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {

                sqlcon.Open();
                string query = $"Select  * from Product  where ProductId = @ProductId";
                SqlDataAdapter sqlDa = new SqlDataAdapter(query, sqlcon);
                sqlDa.SelectCommand.Parameters.AddWithValue("@ProductId", id);
                sqlDa.Fill(dtblProduct);
            }
            if (dtblProduct.Rows.Count == 1)
            {
                productlist.ProductId = Convert.ToInt32(dtblProduct.Rows[0][0].ToString());
                productlist.CategoryId = Convert.ToInt32(dtblProduct.Rows[0][1].ToString());
                productlist.ProductName = dtblProduct.Rows[0][2].ToString();
                productlist.Descriptions = dtblProduct.Rows[0][3].ToString();

                productlist.ProductQuantity = Convert.ToInt32(dtblProduct.Rows[0][4].ToString());

                productlist.ProductPrice = Convert.ToInt32(dtblProduct.Rows[0][5].ToString());

                productlist.ProductImage = dtblProduct.Rows[0][6].ToString();

                productlist.Isavaiable = bool.Parse(dtblProduct.Rows[0][7].ToString());

                productlist.ProductColor = dtblProduct.Rows[0][8].ToString();


                productlist.Isdiscount = bool.Parse(dtblProduct.Rows[0][9].ToString());


                productlist.Taglist = Convert.ToInt32(dtblProduct.Rows[0][10].ToString());


                productlist.ProductSize = dtblProduct.Rows[0][11].ToString();
                return View(productlist);
            }
            else
            {
                return RedirectToAction("MyProducts");

            }

        }

        [HttpPost]

        public ActionResult EditA(Adminproductlist productlist, HttpPostedFileBase file)
        {


            string pic = null;
            if (file != null)
            {


                pic = System.IO.Path.GetFileName(file.FileName);
                string path = System.IO.Path.Combine(Server.MapPath("~/ProductImg/"), pic);
                file.SaveAs(path);
                productlist.ProductImage = pic;
            }
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                string query = "UPDATE Product SET  CategoryId= @CategoryId,ProductName=@ProductName,ProductDescription=@ProductDescription,ProductQuantity=@ProductQuantity,ProductPrice=@ProductPrice,ProductImage=@ProductImage,IsAvilable=@IsAvilable,ProductColor=@ProductColor,DiscountAvailable=@DiscountAvailable,Taglistid=@Taglistid,ProductSize=@ProductSize  where ProductId = @ProductId ";
                SqlCommand sqlCmd = new SqlCommand(query, sqlcon);
                sqlCmd.Parameters.AddWithValue("@ProductId", productlist.ProductId.ToString());

                sqlCmd.Parameters.AddWithValue("@CategoryId", productlist.CategoryId.ToString());

                sqlCmd.Parameters.AddWithValue("@ProductName", productlist.ProductName.ToString());

                sqlCmd.Parameters.AddWithValue("@ProductDescription", productlist.Descriptions.ToString());

                sqlCmd.Parameters.AddWithValue("@ProductQuantity", productlist.ProductQuantity.ToString());

                sqlCmd.Parameters.AddWithValue("@ProductPrice", productlist.ProductPrice.ToString());

                sqlCmd.Parameters.AddWithValue("@ProductImage", pic);

                sqlCmd.Parameters.AddWithValue("@IsAvilable", productlist.Isavaiable.ToString());

                sqlCmd.Parameters.AddWithValue("@ProductColor", productlist.ProductColor.ToString());

                sqlCmd.Parameters.AddWithValue("@DiscountAvailable", productlist.Isdiscount.ToString());

                sqlCmd.Parameters.AddWithValue("@Taglistid", productlist.Taglist.ToString());

                sqlCmd.Parameters.AddWithValue("@ProductSize", productlist.ProductSize.ToString());
                sqlCmd.ExecuteNonQuery();
            }
            return RedirectToAction("MyProducts");



            // return Content(productlist.ProductImage);


        }
    }


}

OnlineShoppingStore/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStore.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GameCategory()
        {
            return View("~/Views/Product/GameDetails.cshtml");
        }
        public ActionResult MenCategory()
        {
            return View("~/Views/Product/MenDetails.cshtml");
        }
        public ActionResult WomenCategory()
        {
            if (Session["loged_in_customer"] != null)
            {
                return View("~/Views/Product/WomenDetails.cshtml");
            }
            return RedirectToAction("Index", "Home");
        }
        public ActionResult ElectronicsCategory()
        {
            return View("~/Views/Product/ElectronicsDetails.cshtml");
        }

        public ActionResult TestDetails()
        {
            return View("~/Views/Product/TestDetails.cshtml");
        }

        



    }
}

OnlineShoppingStore/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

OnlineShoppingStore/Views/Home/Addtocartedit.cshtml
@using OnlineShoppingStore.Models
@{
    ViewBag.Title = "Addtocartedit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@if (Session["cart"] == null)
{
    <div class="alert alert-danger">
        <strong>No product added to cart!</strong>
    </div>

}
else
{
    
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Add</th>
        </tr>
    </thead>
    <tbody>
        @foreach (item item in (List<item>)Session["cart"])
        {
            <tr>
                <td>>@item.ProductCartTable.Rows[0][2]</td>
                <td>@item.Quantity</td>
                <td>
                    @*<a href="@Url.Action("AddToCart", "Home", new { productId = item.ProductCartTable.Rows[0][0] })">*@
                    <a href="../Home/AddToCartinc?id=@item.ProductCartTable.Rows[0][0]">

                        <i class="fa fa-plus"></i>
                    </a>

                    <a href="../Home/DecreaseQty?id=@item.ProductCartTable.Rows[0][0]">

                        <i class="fa fa-minus"></i>
                    </a>
                </td>
            </tr>
        }

    </tbody>
    <button alignment="center" class="main-btn"><a href="../Home/Index">DONE</a></button>
</table>


}

OnlineShoppingStore/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OnlineShoppingStore/Views/Home/DONE.cshtml
@{
    ViewBag.Title = "DONE";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*Response.Write("
<script>alert('Order taken successfully')</script>");*@

<h1>success</h1>

OnlineShoppingStore/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div id="themeSlider" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#themeSlider" data-slide-to="0" class="active"></li>
        <li data-target="#themeSlider" data-slide-to="1"></li>
        <li data-target="#themeSlider" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="item active">
            <div class="imgOverlay"></div>
            <img style="height:320px;width:100%" src="../Images/Slider1.jpg" alt="First slide">
            <div class="carousel-caption">


            </div>
        </div>
        <div class="item">
            <div class="imgOverlay"></div>
            <img style="height:320px;width:100%" src="../Images/Slider2.jpg" alt="Second slide">
            <div class="carousel-caption">


            </div>
        </div>
        <div class="item">
            <div class="imgOverlay"></div>
            <img style="height:320px;width:100%" src="../Images/Slider3.jpg" alt="Third slide">
            <div class="carousel-caption">


            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#themeSlider" data-slide="prev">
        <span class="fa fa-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#themeSlider" data-slide="next">
        <span class="fa fa-chevron-right"></span>
    </a>

</div>
<div class="olContent f1"><h2 style="color:black">Search Product/Category</h2></div>
<div class="olSearch fr">
    <input type="text" placeholder="Enter Keyword" name="searchKey" class="inputComn houseText form-control" />
    <div class="searchIcon">
        <button type="button" class="searchBtn">
            <img src="~/Images/searchIcon.png" />
        </button>
    </div>


</div>

<div class="row">
    <div class="col-md-12">
        <div class="page-header">
            <h1>Category</h1>
        </div>
    </div>
</div>

<div class="row product-container">

    <div class="col-md-3 col-sm-3 col-xs-6" style="margin-bottom:8px">
        <a href="../Home/Products/1">
            <div class="thumbnail product-item" style="height:300px">

                <img class="img-responsive" title="Click to View Product detail"
                     style="cursor:pointer;height:160px;width:100%"
                     src="~/Images/3.jpg" />

                <div class="caption">
                    <h5>Gents Park</h5>

                    <p>Available</p>

                </div>
            </div>
        </a>
    </div>

    


        <div class="col-md-3 col-sm-3 col-xs-6" style="margin-bottom:8px">
            
            <a href="../Home/Products/2">
                <div class="thumbnail product-item" style="height:300px">

                    <img class="img-responsive" title="Click to View Product detail"
                         style="cursor:pointer;height:160px;width:100%"
                         src="~/Images/2.jpg" />

                    <div class="caption">
                        <h5>Ladies Fashion</h5>

                        <p>Available</p>

                    </div>
                </div>
            </a>
        </div>



        <div class="col-md-3 col-sm-3 col-xs-6" style="margin-bottom:8px">
            <a href="../Home/Products/6">
                <div class="thumbnail product-item" style="height:300px">

                    <img class="img-responsive" title="Click to View Product detail"
                         style="cursor:pointer;height:160px;width:100%"
                         src="~/Images/1.jpg" />

                    <div class="caption">
                        <h5>Electronics</h5>

                        <p>Available</p>

                    </div>


                </div>
            </a>
        </div>

        <div class="col-md-3 col-sm-3 col-xs-6" style="margin-bottom:8px">
            
            <a href="../Home/Products/5">
                <div class="thumbnail product-item" style="height:300px">

                    <img class="img-responsive" title="Click to View Product detail"
                         style="cursor:pointer;height:160px;width:100%"
                         src="~/Images/4.jpg" />

                    <div class="caption">
                        <h5>Gaming Products</h5>
                       
                        <p>Available</p>

                    </div>
                </div>
            </a>

        </div>






    </div>

OnlineShoppingStore/Views/Home/Login.cshtml
@*@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/Categorylayout.cshtml";
}*@

@using OnlineShoppingStore.Models
@model LoginViewModel
@{
    ViewBag.Title = "Log in";
}



<!DOCTYPE html>
<html>
<head>
    <title>The Login Form</title>
</head>
<body>
    <div class="wrap">
        <form class="login-form" action="Login">
            <div class="form-header">
                <h3>Login Form</h3>
                <p>Login to access your dashboard</p>
            </div>
            <!--Email Input-->
            <div class="form-group">
                <input name="email" type="text" class="form-input" placeholder="email@example.com">
            </div>
            <!--Password Input-->
            <div class="form-group">
                <input name="pass" type="password" class="form-input" placeholder="password">
            </div>
            <!--Login Button-->
            <div class="form-group">
                <button name="log_sub" value="clicked" class="form-button" type="submit">Log In</button>
            </div>
            <div class="form-footer">
                Don't have an account? <a href="/Account/Register">Sign Up</a>
            </div>
        </form>
    </div><!--/.wrap-->
</body>
</html>

<div class="footer">
    <p>© 2017  Master  Login form. All Rights Reserved | Design by  <a href="https://w3layouts.com/">  w3layouts </a></p>
</div>
</div>

OnlineShoppingStore/Views/Home/Product.cshtml
@{
    ViewBag.Title = "Product";
    Layout = "~/Views/Shared/_myadminlayout.cshtml";
}

<h2>Product</h2>




@for (int i = 0; i < Model.Rows.Count; i++)
{
      int count = 1;
    <div class="col-md-3 col-sm-3 col-xs-6" style="margin-bottom:8px">

        <div class="thumbnail product-item" style="height:300px">

            <img class="img-responsive" title="Click to View Product detail"
                 style="cursor:pointer;height:160px;width:100%"
                 src="~/ProductImg/@Model.Rows[i][6]" />

            <div class="caption">
                <h5>@Model.Rows[i][2]</h5>
                <p>@Model.Rows[i][5]</p>

                <p>@Model.Rows[i][7]</p>

            </div>
        </div>

    </div>
  
    <tr>
        <td>@count</td>
        <td>@Model.Rows[i][2]</td>
        <td>@Model.Rows[i][5]</td>
        @*<td><a href="@Url.Action("Edit,"MyAdmin",new{@productID=@Model.Rows[i][0]})>Edit</a></td> *@

        <td><a href="/MyAdmin/Edit/@Model.Rows[i][0]">Edit</a></td>
    </tr>
    count++;
}

OnlineShoppingStore/Views/Home/Products.cshtml
@{
    ViewBag.Title = "Products";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Products</h2>

@for (int i = 0; i < Model.Rows.Count; i++)
{
    <div class="col-md-3 col-sm-3 col-xs-6" style="margin-bottom:8px">

        <div class="thumbnail product-item" style="height:300px">

            <img class="img-responsive" title="Click to View Product detail"
                 style="cursor:pointer;height:160px;width:100%"
                 src="~/ProductImg/@Model.Rows[i][6]" />

            <div class="caption">
                <h5>@Model.Rows[i][2]</h5>
                <p>@Model.Rows[i][5]</p>

                <p>@Model.Rows[i][7]</p>

            </div>
            <button class="main-btn" onclick="location.href='@Url.Action("AddtoCart", "Home")?id='+@(Model.Rows[i][0]) ">Add To Cart</button>

        </div>

    </div>

    
    }

OnlineShoppingStore/Views/Home/aboutus.cshtml
@{
    ViewBag.Title = "aboutus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <html>

    <head>

        <title>

            biodata saimom

        </title>

    </head>


    <body>
        <div>
            <h1><p align="center">Members</p></h1>
            <p align="left"><img src="saimom.jpg" height="450" width="450"></p>
        </div>

        <h2>Personal Info</h2>

        <ul>

            <li>NAME:MD. SAIMOM Islam</li>
            <li>FATHER'S NAME: KABIR HOSSAIN</li>
            <li>MOTHERS'S NAME: SELINA KABIR</li>
            <li>DATE OF BIRTH: 8<sup>th</sup> SEPTEMBER,1997</li>
            <li>PERMANENT ADDRESS:RAMGANJ,LUXMIPUR,TEORY</li>
            <li>CONTACT NUMBER:01521400864</li>

        </ul>

        <h3>EDUCATIONAL BACKGROUND</h3>
        <ul>

            SSC
            <li>SCHOOL:CHITTAGONG GOVT. HIGH SCHOOL</li></br>
            <li>PASSING YEAR:2014</li></br>
            <li>GPA:5.00</li></br></br>

            HSC
            <li>COLLEGE:CHITTAGONG B.A.F SHAHEEN COLLEGE</li></br>
            <li>PASSING YEAR:2016</li></br>
            <li>GPA:4.67</li>

        </ul>



    </body>





    </html>

OnlineShoppingStore/Views/Home/regform.cshtml
@{
    ViewBag.Title = "regform";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <title>Bootstrap Simple Login Form with Blue Background</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style type="text/css">
        body {
            color: #fff;
            background: #3598dc;
            font-family: 'Roboto', sans-serif;
        }

        .form-control {
            height: 41px;
            background: #f2f2f2;
            box-shadow: none !important;
            border: none;
        }

            .form-control:focus {
                background: #e2e2e2;
            }

        .form-control, .btn {
            border-radius: 3px;
        }

        .signup-form {
            width: 390px;
            margin: 30px auto;
        }

            .signup-form form {
                color: #999;
                border-radius: 3px;
                margin-bottom: 15px;
                background: #fff;
                box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
                padding: 30px;
            }

            .signup-form h2 {
                color: #333;
                font-weight: bold;
                margin-top: 0;
            }

            .signup-form hr {
                margin: 0 -30px 20px;
            }

            .signup-form .form-group {
                margin-bottom: 20px;
            }

            .signup-form input[type="checkbox"] {
                margin-top: 3px;
            }

            .signup-form .row div:first-child {
                padding-right: 10px;
            }

            .signup-form .row div:last-child {
                padding-left: 10px;
            }

            .signup-form .btn {
                font-size: 16px;
                font-weight: bold;
                background: #3598dc;
                border: none;
                min-width: 140px;
            }

                .signup-form .btn:hover, .signup-form .btn:focus {
                    background: #2389cd !important;
                    outline: none;
                }

            .signup-form a {
                color: #fff;
                text-decoration: underline;
            }

                .signup-form a:hover {
                    text-decoration: none;
                }

            .signup-form form a {
                color: #3598dc;
                text-decoration: none;
            }

                .signup-form form a:hover {
                    text-decoration: underline;
                }

            .signup-form .hint-text {
                padding-bottom: 15px;
                text-align: center;
            }
    </style>
</head>
<body>
    <div class="signup-form">
        <form action="regform">
            <h2>Sign Up</h2>
            <p>Please fill in this form to create an account!</p>
            <hr>
            <div class="form-group">
                <div class="row">
                    <div class="col-xs-6"><input type="text" class="form-control" name="first_name" placeholder="First Name" required="required"></div>
                    <div class="col-xs-6"><input type="text" class="form-control" name="last_name" placeholder="Last Name" required="required"></div>
                </div>
            </div>
            <div class="form-group">
                <input type="email" class="form-control" name="email" placeholder="Email" required="required">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password" placeholder="Password" required="required">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="confirm_password" placeholder="Confirm Password" required="required">
            </div>
            <div class="form-group">
                <label class="checkbox-inline"><input type="checkbox" required="required"> I accept the <a href="#">Terms of Use</a> &amp; <a href="#">Privacy Policy</a></label>
            </div>
            <div class="form-group">
                <button type="submit" name="reg_submit" value="clicked" class="btn btn-primary btn-lg">Sign Up</button>
            </div>
        </form>
        <div class="hint-text">Already have an account? <a href="/Account/Login">Login here</a></div>
    </div>
</body>
</html>